- Gopkg.lock
- Gopkg.toml
Added override clause with fixed version for package contrib.go.opencensus.io/exporter/ocagent
> Override ocagent with fixed version

- pkg/models/service_indicators.go
This is to support any type of indicator source, not only prometheus
> #850 allow indicator query to be of arbitrary type

- .gitignore
- pkg/api/utils/apiServiceUtils.go
I have an undebuggable issue on travis-CI when authenticating with keptn, where the API seems to not return JSON.
The error message displayed is: ``unexpected end of JSON input``
My guess is that this is an issue with istio or a loadbalancer or alike. To be 100% sure, I've added a proper debug output of the body.
Also, we can never be 100% sure that the response contains proper JSON.
> Add more information about json parse errors

- pkg/events/keptnEvents.go
We need deployment strategy in several events for the quality gates standalone use case.
In fact, gatekeeper, pitometer and jmeter already use this field, but it is not specified within this package.
> #950 added deployment strategy to several events

- pkg/events/keptnEvents.go
During testing I noticed that when setting `success: false` for SLI Results is not populated within JSON.
As a user I would expect `success: false` to be shown in the result if something failed.
> #950 fix success:false should not be ommitted

- pkg/events/keptnEvents.go
in the evaluation results, now all evaluated criteria and their target values are listed, instead of just the violations
> #1053 added SLO config to evaluationdetails and restructured eval details

- .travis.yml
- README.md
I've changed .travis.yml such that it would automatically create a PR on keptn/keptn for all sub-directories that contain a file called `go.mod` which contains `go-utils`.
The resulting PR looks like this: https://github.com/keptn/keptn/pull/1427
I've set it up such that if we create a new tag (e.g., v0.6.1), the script should use the tag instead of the commit hash (though we'd have to try that out).
> Added automation for PRs to Keptn

- .travis.yml
- Check for `go-utils` was improved to check for the whole name of the package
- Added some `|| true` to the commands to allow for failures
- Added some `|| travis_terminate 1` to the commands to ensure travis fails if the command fails
> Improve auto-PR

- pkg/api/utils/stageUtils.go
Hi,
while trying to implement https://github.com/keptn/keptn/issues/1624 I could not get alls stages for a project with
```
stagesHandler := apiutils.NewAuthenticatedStageHandler(endPoint.String(), apiToken, "x-token", nil, *scheme)
stages, err := stagesHandler.GetAllStages(*projectName.project)
```
Looks like the API Url is wrong (in projectUtils.go it's already using the /configuration-service/ URL).
I've adjusted the URL and tested locally, seems to be working.
I don't know if this is an issue as well, but in the projectUtils.go and serviceUtils.go there is the httpClient.Transport = getClientTransport() while in the stageUtils.go it is not.
projectUtils.go
```
func NewAuthenticatedProjectHandler(baseURL string, authToken string, authHeader string, httpClient *http.Client, scheme …
```
> Fix api endpoint

- pkg/api/utils/eventUtils.go
The event type filter was not set properly in the `GetEvents()` function
> added event type filter to request params

- pkg/lib/events.go
The struct for the `action.triggered` event implemented in PR #162 did not contain the correct definition for the `action` property. Additionally, constants for the result/status of an action have been added.
> fixed struct of action.triggered event; added constants for result info

- pkg/lib/events.go
changed the type of `Value` of the action definition to `interface{}` to be more flexible
> #1816 fixed struct of action.triggered event

- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/stageUtils.go
This PR fixes https://github.com/keptn/keptn/issues/1861.
Applied rule:
- If the go-utils user creates an **authenticated** handler, we use the configuration-service URL suitable for the api-gateway-nginx (i.e. containing `/configuration-service` as prefix).
- If the go-utils user creates a normal handler, we use the **internal** configuration-service URL.
> #1861 Fix configuration-service URL

- pkg/lib/events.go
This PR prepares https://github.com/keptn/keptn/issues/1881 and https://github.com/keptn-contrib/unleash-service/issues/8 by adding an `action.started` event.
Furthermore, this PR streamlines the "event" vs "events" naming.
> #1881 Add action started event

- pkg/api/utils/apiUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/stageUtils.go
**Status:**
In the Keptn API, the `api-service` and the `configuration-service` provide endpoints with the same paths. However, their implementation is different, which led to confusion.
In order to allow a clear distinction also in the go-utils helper function, this PR introduces a new handler, which handles requests for the `api-service` (i.e. POSTs and DELETEs on projects and POSTs on services).
> #1881 Introduce apiUtils 

- pkg/lib/combined_logger.go
- pkg/lib/keptn.go
- pkg/lib/keptn_test.go
This PR is part of [#1607](https://github.com/keptn/issues/1607).
When a Keptn Handler is being initialized, a logger is automatically initialized. By default, a standard logger that only prints to stdout is initialized. There is also an option to create a WebSocket logger, based on the Websocket connection info within the data block of the incoming CloudEvent. By default, when connecting to a WebSocket server, the endpoint is set to `ws://api-service.keptn.svc.cluster.local:8080`. This can be overriden in the options provided to the `NewKeptn` function. Example:
```
serviceNameForLogging := "my-service"
customWebsocketEndpoint := "ws://my-custom-endpoint"
keptnHandler, _ := keptn.NewKeptn(incomingCloudEvent, &KeptnOpts{
UseLocalFileSystem:      false,
ConfigurationServiceURL: …
```
> #1607 create a logger when a Keptn Handler is being initialized

- pkg/api/models/keptn_context_extended_c_e.go
- pkg/lib/events.go
Addresses https://github.com/keptn/keptn/issues/1815
In order to be spec-compliant, the triggeredid is moved into the CloudEvents context.
> #1815 Move triggeredid into header

- pkg/lib/remediations.go
- pkg/lib/v0_1_3/remediations.go
- pkg/lib/v0_1_4/remediations.go
This PR prepares https://github.com/keptn/keptn/issues/1919
More precisely, this PR 
- replaces the field `version` with `apiVersion` in the remediation type and
- reorganizes the package structure, i.e. moves the `spec.keptn.sh/0.1.3`-compatible remediation types into the folder `v0_1_3`.
> #1919 Use apiVersion for Remediation types, re-organize package structure

- pkg/lib/v0_1_4/remediations.go
The yaml tag for `apiVersion` was set to `version`
> Fixed apiVersion yaml tag

- pkg/api/utils/resourceUtils.go
To implement the behaviour described in [#1480](https://github.com/keptn/issues/1480), we need to distinguish between 404 errors and any other types of errors when trying to fetch a service resource
> #1480 add dedicated error object for resource 404 responses

- pkg/api/utils/eventUtils.go
- Passing page size parameter to `getEvents` function for controlling the number of returned events
> Added page size parameter to event filter

- pkg/lib/datastore.go
When an event could not be found, a HTTP 400 response was sent previously. This has been changed to 404
> #1655 set error code to 404 if no event could be found

- pkg/lib/v0_2_0/deployment.go
- pkg/lib/v0_2_0/evaluation.go
- pkg/lib/v0_2_0/release.go
- pkg/lib/v0_2_0/test.go
This PR adds the Git commit hash in deployment-, test-, evaluation-, and release-finished.events.
This allows to exactly know which version was deployed, what test was performed, which SLOs have been used, and what is the released version.
> #2107 Add Git commit in CloudEvents

- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/events_test.go
The retry mechanism was not working properly when an http error code was received. This has been fixed and a unit test has been added.
> Fix retry mechanism of sending events

- pkg/lib/events.go
- pkg/lib/events_test.go
Implements a missing function for sending SLI done events. This will help folks implementing their own SLI Providers
> adding SendInternalGetSLIDoneEvent

- README.md
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
This PR removes the Travis-CI Badge and adds a GH action badge.
> Added GH actions badge

- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/events_test.go
`mapstructure.Decode()` didn't seem to work correctly when the structure contains a nested `map[string]interace{}` property - this is the case for e.g. the `ConfigurationChange` struct: https://github.com/keptn/go-utils/blob/b4da7753f6f2d95dfe3ebb65064d15c4564ebdee/pkg/lib/v0_2_0/configuration_change.go#L3
> Use json.marshal/unmarshal instead of mapstructure.Decode

- pkg/lib/v0_2_0/remediation.go
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
It looks like RemediationTaskName is missing (all other CEs seem to have a TaskName variable).
spec entry: https://github.com/keptn/spec/blob/0.2.0-alpha/cloudevents.md#remediation
> Added remediation task name

- pkg/lib/v0_2_0/evaluation.go
Related to [#2478 SLI evaluation breakdown as barista table (#3023)](https://github.com/keptn/keptn/pull/3053)
Modified `SLIEvaluationResult`
- Split `Targets` into `PassTargets` and `WarningTargets`
- Added property `KeySLI`
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>
> split sli-targets, add key-sli

- pkg/lib/v0_2_0/endpoints.go
Needed for https://github.com/keptn/keptn/issues/3757
> Added endpoints struct

- pkg/lib/cmdUtils.go
This an extension needed for https://github.com/keptn-sandbox/locust-service/issues/25. Allows the locust execute command to add additional environment variables.
> Add function ExecuteCommandWithEnv that appends the given env to the env of the command to be executed

- pkg/common/timeutils/timeutils.go
- pkg/common/timeutils/timeutils_test.go
- pkg/lib/v0_2_0/evaluation.go
Needed for https://github.com/keptn/keptn/issues/4079
> #4079 function for generating start and end timestamps; timeframe in evaluation.triggered data

- pkg/common/retry/retry.go
- pkg/common/retry/retry_test.go
This PR adds a `retry` package to common utils usable for executing actions repeatedly until the succeed. (e.g. retry http request,...)
> Common Utils: Added retry package

- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/events_test.go
- pkg/lib/v0_2_0/keptn.go
fixes https://github.com/keptn/keptn/issues/3408
I've also added the `TestSender` implementation to go-utils
>  Always set shkeptnspecversion when sending a cloudevent

- .github/workflows/auto-pr.yml
- gh-actions-scripts/auto-update-go-mod.sh
**This PR**
* adds some small enhancements to the auto update so that transient dependencies are updated and then tidied up
* removes the unnecessary matrix from the GH actions pipeline
* exchanges manual git commit/push/PR steps for an off-the-shelf GH action
Fixes keptn/keptn#4341
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
> keptn/keptn#4341 add go mod auto update enhancements, update pipeline

- pkg/lib/keptn/keptn_base.go
- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/fake/events.go
This PR adds a go context to the EventSender interface Method as an agument, to control the behavior of the send event logic.
> Added EventSender context

- .github/pull_request_template.md
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- adds a new pipeline to create **prereleases**
- creates pre-releases with version numbers according to the following naming scheme:
- if new version would be `0.9.0`, the pre-release version will be `0.9.0-next.N` with increasing numbers for `N` with every new pre-release until a new actual release is created
- switches the **release** pipeline to create draft releases instead of public releases. The pipeline will still create a release commit and and a tag though ⚠️
Fixes keptn/keptn#4762
> ci: Add pre-release pipeline that can be triggered manually (#4762)

- .github/dependabot.yml
- Updates the dependabot config to follow the new commit message scheme
> build: Update dependabot config to adhere to new commit message scheme

- pkg/api/utils/apiServiceUtils.go
Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
- ensures that `http.Client` instances respect the standard go HTTP proxy settings even when using a custom `http.Transport` by adding `Proxy: http.ProxyFromEnvironment` to the `Transport`
While probably not an issue in most places, it caused some inconsistent behavior in the dynatrace-service.
Might be useful for adding proxy support for other components using go-utils.
> fix: http clients should support standard proxy settings

- pkg/api/models/secret.go
Part of https://github.comkeptn/keptn/issues/4749
> feat: Extended secret API model with list of available keys in the secret (#4749)

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- fixes the auto-release workflow which had issue with branch protection rules during the automatic push of the release commit
- adds a title to the GitHub Release which is the same as the tag name
> ci: fix branch protection during releases, add release title

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- fixes a bug in the release pipeline that led to the behaviour that changes from a pre-release were not picked up again for a following full release (in the changelog)
- removes unnecessary use of the `branch-protection-bot`
> ci: Fix issue where release changelog would not contain changes that were in an earlier pre-release

- pkg/api/models/keptn_context_extended_c_e.go
- pkg/api/models/keptn_context_extended_c_e_test.go
This PR adds the possibility to easily add "temporary/additional" data to a `KeptnContextExtendedCE`.
Temporary data will be added under the `data  -> temporaryData` section of an event. Each source can add temporary data with a given `key`. The temporary data itself is unstructured. 
Example with key name `distributor` :
> feat: add temporary data to keptn event

- pkg/common/mongoutils/mongo.go
- pkg/common/mongoutils/mongo_test.go
* updates the mongo DB env variable so that it follows the new naming scheme that is used in the mongodb-datastore helm chart in keptn/keptn
Part of keptn/keptn#4801
> feat: Update mongo DB env variables to new names according to new variables in installer chart

- .github/workflows/pre-release.yml
- pkg/common/timeutils/timeutils.go
- pkg/common/timeutils/timeutils_test.go
-  change time parsing to a custom one to avoid parsing errors
-  In the order we try :
- ISO8601 :  000Z format
-  then RFC3339 : "2019-10-12T07:20:50.52Z" 
- finally a fallback userfriendly format : "2006-01-02T15:04:05"
https://github.com/keptn/keptn/issues/4788
RFC 3339 is following the ISO 8601 DateTime format. The only difference is RFC allows us to replace “T” with “space”
> feat: added custom time parsing (keptn/keptn#4788)

- pkg/lib/v0_2_0/fake/events.go
In some cases unit tests where the fake event sender is being used were failing because the event sender internally uses the `append()` function to gather the sent events. However this function is not thread safe, which is why a lock has been added
> fix: Make fake event sender thread safe by adding a lock

- pkg/api/utils/uniformUtils.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
-  avoids sending malformed pings
keptn/keptn#6309
> fix: if the integrationId is not set we should not ping (keptn/keptn#6309)

- pkg/api/utils/apiUtils.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
- pkg/lib/datastore.go
> fix: Adding missing error checks

- pkg/api/utils/apiServiceUtils.go
- pkg/api/utils/apiServiceUtils_test.go
- pkg/api/utils/apiUtils.go
- pkg/api/utils/authUtils.go
- pkg/api/utils/client.go
- pkg/api/utils/client_test.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/logUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/secretUtils.go
- pkg/api/utils/sequenceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
- pkg/api/utils/uniformUtils.go
This PR aims to add a more convenient way to retrieve Keptn API compeonents, especially when working with multiple APIs.
Usage: initialize ApiSet once (like you've done before for a specific handler), e.g.:
```go
apiset, err := apiutils.NewAPISet(baseURL, authToken, authHeader, client, scheme)
``` 
then use the `apiset` to retrieve APIs of interest to work with: e.g.:
```go
apiset.ProjectsV1().GetProject(project)
apiset.SecretsV1().CreateSecret(secret)
...
```
> feat: introducing `APISet` for more convenient access to keptn APIs

- pkg/api/utils/client.go
- pkg/api/utils/client_test.go
This PR enhances the configuration of an APISet.
Previously the constructor method for an APISet had quite some arguments which all needed to be passed by the user:
```
apiutils.NewAPISet(baseURL, authToken, authHeader, client, scheme)
```
Now, the only required argument to pass is `baseURL`. Additionally the constructor method was renamed to just `New()`
```
apiutils.New(baseURL)
```
The equivalent way of creating a APISet like above would be:
```
apiutils.New(baseURL, WithAuthToken(authToken),WithClient(client))
``` 
:exclamation: Note that this API is not yet released and is only used in CLI so far, for which a follow-up PR will be made.
> chore: enhance configuration of APISet

- pkg/api/utils/resourceUtils.go
- pkg/api/utils/resourceUtils_test.go
- pkg/api/utils/stageUtils.go
- reverts breaking changes from [here](https://github.com/keptn/go-utils/pull/375/commits/ba5397b5d46f26791220d1ae4af4991190bdf934)
-  deprecates resource functions in favor of a single one per method 
keptn/keptn#6349
sdk and shipyard interfaces need to be updated again if we do this 👼
> fix: Revert old getters and deprecate them

- pkg/api/models/create_project.go
- pkg/api/models/project.go
- Adds SSH publicKey auth support
Fixes [#6800](https://github.com/keptn/keptn/issues/6800)
> feat: Add SSH publicKey auth support

- pkg/api/models/error.go
- pkg/api/utils/apiServiceUtils.go
- pkg/api/utils/client.go
- pkg/api/utils/client_test.go
- pkg/common/testutils/httpclient.go
This PR 
* just adds a missing method to Keptn interface used for APISet implementations.
* prevents a potential nil pointer panic in models/error.go
* adds a testutil package with a simple HTTP client mock
Adaptions to the CLI are included in this PR: https://github.com/keptn/keptn/pull/6729
> fix: Add missing Method to KeptnInterface/APISet

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- .github/workflows/tests.yml
- go.mod
- go.sum
- upgrades go-utils to Go 1.17
> chore: Update to Go 1.17

- pkg/api/models/expanded_project.go
- pkg/api/models/expanded_projects.go
- pkg/api/models/expanded_service.go
- pkg/api/models/expanded_services.go
- pkg/api/models/expanded_stage.go
- pkg/api/models/expanded_stages.go
- pkg/api/models/remediation.go
- pkg/api/models/sequencecancellation.go
- pkg/api/models/sequencecontrol.go
- pkg/api/models/state.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
- moves shared models from shipyard 
keptn/keptn#5811
> chore: Moved common models from shipyard to go-utils

- pkg/api/models/expanded_project.go
- adds proxy auth parameters to ExpandedProject struct
> feat: Introduce proxy parameters to ExpandedProject struct

- pkg/lib/v0_2_0/fake/events.go
- Fix error message in `EventSender.AssertSentEventTypes()` when the length of expected and actually sent couldevents type is different.
Write a simple go test using AssertSentEventTypes and pass a number of expected events different from the number of actual Send calls, e.g.
```
...
fakeEventSender := &keptnfake.EventSender{}	
assert.NoError(
t, fakeEventSender.AssertSentEventTypes(
[]string{
"sh.keptn.event.action.started", "sh.keptn.event.action.finished",
},
),
)
```
Before fix:
```
Error:      	Received unexpected error:
expected 0 event, got 2
```
After fix:
```
Error:      	Received unexpected error:
expected 2 event, got 0
```
> fix: correct error message in fake/EventSender.AssertSentEventTypes

- pkg/api/utils/healthCheck.go
- pkg/api/utils/healthCheck_test.go
This PR introduces the option to provide a condition for the health endpoint, as well as the path that should be used for that endpoint, using the following options:
```
WithReadinessConditionFunc
WithPath
```
> feat: Provide option to specify readiness condition

- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/events_test.go
This PR provides an option to configure the number of retries that are performed when trying to send a cloud event. Also, the error message has been adapted to give more insights on why an event could not be sent successfully
> feat: Added option for configuring number of retries for http event sender, as well as additional logging

- pkg/api/utils/apiUtils.go
This PR fixing a potential problem in the `APIHandler` when used with `InternalAPISet`:
Request URIs are not being built correctly: Examples:
* CreateService builds the URI http://shipyardcontroller:8080/controlPlane/v1/project/{PROJECT}/service, rather than http://shipyardcontroller:8080/v1/project/{PROJECT}/service . I.e. would be offered by the shipyard-controller but the URI is wrong.
* GetMetadata builds the URI http://shipyardcontroller:8080/v1/metadata . I.e. is not offered by the shipyard controller, so can't work whatever the URI.
> fix: Fixed wrong paths for apiutils

- pkg/api/utils/apiUtils.go
- pkg/api/utils/apiUtils_test.go
This PR fixes the logic for adapting the path for calls to the API service.
Previously, calls to the API service were resulting in the following baseURL being used:
`<api-url>/api/api/v1`
> fix: Set the path properly for calls to api-service

- pkg/api/utils/apiUtils.go
- pkg/api/utils/apiUtils_test.go
> fix: Set the path properly for calls to api-service 

- pkg/api/models/uniform.go
- removes subscription
keptn/keptn#7364
> chore(go-utils): Removed deprecated subscription from uniform

- pkg/api/utils/apiUtils.go
- pkg/api/utils/authUtils.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/logUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/secretUtils.go
- pkg/api/utils/sequenceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
- pkg/api/utils/uniformUtils.go
- pkg/api/utils/v2/uniformUtils.go
This PR makes sure the api handler objects are set before they are used. Otherwise we have the danger of breaking something if the v1 API handlers have been initialized directly, instead of via the constructor methods
> fix: Make sure all api handlers are set when using v2 api handlers in v1

- pkg/api/utils/v2/resourceUtils.go
- Removes a trailing `/` from the URL that is created in the `GetAllServiceResources` to fix the resources not found errors in Keptn 0.16.0
- keptn/keptn#8160
> fix: Make GetAllServiceResources compatible with Keptn 0.16.0+

- pkg/common/kubeutils/endpoint_provider.go
- pkg/common/kubeutils/endpoint_provider_test.go
Signed-off-by: Nitanshu Vashistha <nitanshu.vzard@gmail.com>
Replaces the deprecated  "k8s.io/api/extensions/v1beta1" API with "k8s.io/api/networking/v1"
Fixes [#4432](https://github.com/keptn/keptn/issues/4432)
> feat: Use NetworkingV1 instead of deprecated ExtensionsV1beta1

- pkg/sdk/connector/controlplane/controlplane.go
- pkg/sdk/connector/nats/nats.go
- pkg/sdk/connector/subscriptionsource/subscriptionsource.go
- pkg/sdk/connector/subscriptionsource/subscriptionsource_test.go
closes: https://github.com/keptn/keptn/issues/8202
I did not implement this part, tho: 
as the nats library is handling connection issues transparently, and there is no need to shutdown / restart the pod.
> feat(go-utils): Added retry logic to cp-connector for contacting Keptn's control plane for registration and renewal of such

- pkg/sdk/keptn.go
- pkg/sdk/keptn_fake.go
- pkg/sdk/keptn_test.go
- pkg/sdk/taskregistry.go
closes https://github.com/keptn/keptn/issues/8718
This PR introduces the possibility to skip automatic event responses (sending of started/finished events by the sdk) on a per task handler basis. 
Usage:
```go
log.Fatal(sdk.NewKeptn(
serviceName,
sdk.WithTaskEventHandler(
echoTriggeredEventType,
NewEchoHandler(), sdk.TaskHandlerOptions{
SkipAutomaticResponse: true,
}),
sdk.WithLogger(logrus.StandardLogger()),
).Start())
```
> feat: Introduce skipping of automatic event responses per task handler

- pkg/sdk/connector/controlplane/controlplane.go
- pkg/sdk/connector/controlplane/controlplane_test.go
- pkg/sdk/connector/eventsource/http/http.go
- pkg/sdk/connector/eventsource/http/utils.go
- pkg/sdk/connector/eventsource/http/utils_test.go
- pkg/sdk/connector/types/types.go
- pkg/sdk/internal/api/initializer.go
fixes https://github.com/keptn/keptn/issues/8875
Additionally, this PR contains logging improvements of the go-sdk, meaning that it will output a log message containing the currently subscribed events. at INFO level only if the current subscriptions have been changed.
> fix: Fix event handling for duplicated subscriptions in `go-sdk` remote execution plane use case
