keptn/go-utils

- pkg/utils/fileUtils.go
- pkg/utils/kubeUtils.go
Utility functions for
- checking the deployment availability using the kube library
- receiving the keptn directory
> # Utility functions 

- pkg/utils/kubeUtils.go
- Obtaining of deployment failed. Add a retry
> Retry to obtain deployment

- pkg/utils/cmdUtils.go
> #644 added function to execute commands from within a specified directory

- pkg/utils/combined_logger.go
- pkg/utils/logger.go
> #747 Combined logger

- .travis.yml
- Gopkg.lock
- README.md
Added basic travis-ci automated tests for this repo.
> #944 Added travis tests

- pkg/configuration-service/utils/resourceUtils.go
For some reason, the query parameter 'nextKeyPage' was not correctly set.
> #1048 Fixed the handling of the query parameter 'nextKeyPage'

- pkg/events/keptnEvents.go
* SLI Events need the field TestStrategy
* TestsFinishedEventData needs start and end date
> #950 added test-strategy to sli events

- releasenotes/releasenotes_V0.4.0.md
Releases notes for 0.4.0 release
> #1059 added release notes

- pkg/events/keptnEvents.go
Added the "deployment" field as described here: https://github.com/keptn/keptn/issues/1161
> #1161 Added deployment to get sli events

- pkg/events/keptnEvents.go
Added the result property to TestsFinishedEventData, as approved by the keptn/spec change in this [PR](https://github.com/keptn/spec/pull/15).
> #542 Added the result property to TestsFinishedEventData

- pkg/api/utils/apiServiceUtils.go
* #1464 Add log message with Keptn context
> Add log message of Keptn context (#143)

- pkg/utils/keptnUtils.go
* Add a helper function for checking dir names
> #1465 Utility for checking directory names

- pkg/lib/approval_strategy.go
- pkg/lib/canary_action.go
- pkg/lib/events.go
- pkg/lib/shipyard.go
This PR implements the events, as well as the shipyard structure related to the approval workflow defined in [PR 26 of the Keptn spec](https://github.com/keptn/spec/pull/26).
> #1757 added approval events

- pkg/api/models/project.go
- pkg/api/models/service.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/stageUtils.go
I've added the creationDate to the models for project and service, and fixed the configuration-service URL for the getAllSevices function.
> Adding CreationDate to models

- releasenotes/releasenotes_develop.md
> Added empty release notes after the 0.6.2 release

- pkg/lib/events.go
This PR implements the `action.triggered`and `action.finished` events added in [SPEC 31](https://github.com/keptn/spec/pull/31)
> #1816 added definitions for action.triggered and action.finished events

- pkg/lib/events.go
This PR implements the go structs for the remediation events specified in [SPEC 31](https://github.com/keptn/spec/pull/31)
> #1848 added remediation events

- pkg/lib/events.go
- pkg/lib/remediations.go
This PR implements the remediation specification v0.2.0, according to [SPEC 31](https://github.com/keptn/spec/pull/31/files)
> #1848 added remediation structs according to spec

- go.mod
- pkg/api/utils/apiServiceUtils.go
- pkg/api/utils/projectUtils.go
For https://github.com/keptn/keptn/issues/1517 I have to add the function to utilize the new configuration-service endpoint and as this endpoint is using PUT as HTTP method, I had to add this to the apiServiceUtils as well.
> Adding UpdateConfigurationServiceProject and PUT function

- pkg/api/utils/apiUtils.go
- pkg/api/utils/authUtils.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/stageUtils.go
- pkg/lib/events.go
Depending on if we have an authenticated event handler, or if it is used from inside the cluster, the base URL has to be set accordingly
> differentiate between authenticated and internal event handler

- .travis.yml
This PR fixes the auto-update of keptn/go-utils on keptn/keptn
> Fix auto update to master branch

- pkg/api/utils/eventUtils.go
- Getting a specific amount of events using the number of pages and page size parameters
> Added number of pages parameter for getting a specific amount of events

- pkg/lib/v0_2_0/shipyard.go
This PR creates a struct for the shipyard according to the spec change: https://github.com/keptn/spec/pull/36
> #2016 Struct for next generation of shipyard

- pkg/lib/v0_2_0/approval.go
- pkg/lib/v0_2_0/deployment.go
- pkg/lib/v0_2_0/evaluation.go
- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/problemdetails.go
- pkg/lib/v0_2_0/release.go
- pkg/lib/v0_2_0/remediation.go
- pkg/lib/v0_2_0/result.go
- pkg/lib/v0_2_0/status.go
- pkg/lib/v0_2_0/test.go
This PR introduces data structs for the services in the execution plane.
> #2107 Next gen cloud events

- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/stageUtils.go
- pkg/lib/combined_logger.go
- pkg/lib/events.go
- pkg/lib/logger.go
Additionally, this PR improves the error messages and adds "Terminate" to the LoggerInterface.
> #2199 Add sh.keptn.internal.event.service.delete

- pkg/api/utils/serviceUtils.go
Added a helper function to delete a service from the configuration service
> #2199 added delete service function

- pkg/api/models/resource.go
- swagger.yaml
Added the following properties to the `Resource` structs:
- upstreamURL
- version
- branch
> #2307 Added resource metadata to resource structs

- pkg/lib/events.go
- pkg/lib/v0_2_0/evaluation.go
This PR adds a list of event IDs that were used for comparison-based evaluations of SLOs
> #2388 added property for comparison event IDs

- README.md
- releasenotes/releasenotes_V0.7.2.md
- releasenotes/releasenotes_develop.md
Added release notes for release 0.7.2
> Release 0.7.2

- pkg/lib/deployment_strategy.go
- pkg/lib/v0_2_0/action.go
- pkg/lib/v0_2_0/configuration_change.go
- pkg/lib/v0_2_0/deployment.go
- pkg/lib/v0_2_0/release.go
- pkg/lib/v0_2_0/service_create.go
- pkg/lib/v0_2_0/service_delete.go
This PR introduces new CE, which are used for implementing shipyard v0.2
> #2107 Add the deployment strategy in the release triggered event

- pkg/api/models/keptn_context_extended_c_e.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/lib/v0_2_0/approval.go
This PR adds minor extensions/fixes needed to support the delivery assistant workflow in Keptn 0.8. See [#2533](https://github.com/keptn/keptn/issues/2533)
> #2533 Adaptations for the delivery assistant workflow

- pkg/lib/v0_2_0/configure_monitoring.go
> Added events for configure-monitoring task

- pkg/api/utils/eventUtils.go
> Added GetEventsWithRetry function

- pkg/lib/keptn/keptn_base.go
> Fixed sli retrieval error handling

- releasenotes/releasenotes_V0.8.0-alpha.md
> Release notes for v0.8.0-alpha

- pkg/api/utils/eventwatch.go
> removed log.fatal

- pkg/lib/events.go
> #2830 readded ProblemEventType

- pkg/api/models/project.go
- swagger.yaml
> added shipyard version to project model

- pkg/api/utils/projectUtils.go
- pkg/api/utils/serviceUtils.go
This PR adapts this module to the changes made in https://github.com/keptn/keptn/issues/2999
> #2999 remove configurationService path from project and service API

- pkg/api/utils/stageUtils.go
reflects the changes made in https://github.com/keptn/keptn/issues/2999
> removed automatic addition of /configuration-service from stage api client

- go.mod
- go.sum
Reverted the update of several openapi dependencies because they caused problems in combination with other dependencies: https://github.com/keptn/keptn/pull/3242/checks?check_run_id=1880405773#step:5:16
> Fixed openapi dependencies

- pkg/api/utils/apiUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
Needed for https://github.com/keptn/keptn/issues/3001
> #3001 append shipyard controller path to baseURL of authenticated api clients

- pkg/lib/v0_2_0/shipyard.go
> triggerdOn as list instead of map

- pkg/lib/v0_2_0/rollback.go
> added rollback task event data

- pkg/lib/v0_2_0/shipyard.go
> added omitempty to triggeredOn in shipyard struct

- pkg/lib/v0_2_0/events.go
Related to https://github.com/keptn/spec/issues/55
> Added GetInvalidatedEventType() function

- pkg/lib/keptn/keptn_base.go
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
per https://github.com/keptn/go-utils/pull/253#discussion_r574491418
> spelling: validate

- pkg/api/models/keptn_context_extended_c_e.go
- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/keptn.go
- pkg/lib/v0_2_0/keptn_test.go
- swagger.yaml
Needed for https://github.com/keptn/keptn/issues/2982
> #2982 added shkeptnspecversion property

- releasenotes/releasenotes_V0.8.0.md
> Prepare 0.8.0 release

- pkg/lib/service_level_objectives.go
- pkg/lib/v0_2_0/evaluation.go
Related to [keptn/keptn/#3345](https://github.com/keptn/keptn/issues/3345)
> #3345 sli display name

- pkg/lib/keptn/keptn_base.go
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
Fixes one part of https://github.com/keptn/keptn/issues/3447 by removing file i/o from `GetKeptnResource`
> #3447 Remove file i/o from GetKeptnResource

- pkg/lib/v0_2_0/getsli.go
fixes https://github.com/keptn/spec/issues/72
> added Deployment field to GetSLITRiggeredEventData

- releasenotes/releasenotes_V0.8.1.md
- releasenotes/releasenotes_develop.md
> Prepare release 0.8.1

- pkg/api/utils/secretUtils.go
> changed "secrets" path to "secret"

- releasenotes/releasenotes_V0.8.2.md
> merge release 0.8.2 changes to master

- pkg/lib/keptn/keptn_base.go
Part of [#3447](https://github.com/keptn/keptn/issues/3447)
> #3447 GetKeptnResource(): return []byte instead of string

- releasenotes/releasenotes_V0.8.1.md
- releasenotes/releasenotes_develop.md
> added empty release notes

- releasenotes/releasenotes_V0.8.3.md
Signed-off-by: ermin.muratovic <ermin.muratovic@gmail.com>
> Release 0.8.3

- .github/workflows/auto-pr.yml
- .github/workflows/reviewdog.yml
- .github/workflows/tests.yml
- go.mod
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
Implements part of keptn/keptn#2936
Upgrading to Go 1.16
> keptn/keptn#2936 Go Version 1.16 support

- releasenotes/releasenotes_V0.8.4.md
> Updated release notes

- releasenotes/releasenotes_V0.8.4.md
> Prepare release 0.8.4

- pkg/api/models/uniform.go
- pkg/api/models/uniform_test.go
closes: https://github.com/keptn/keptn/issues/4033
> Introduce uniform model

- pkg/lib/keptn/logger.go
Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
> Add functions for logger formatting

- pkg/api/models/secret.go
- pkg/api/utils/fake/secret_handler_mock.go
- pkg/api/utils/secretUtils.go
Parat of https://github.com/keptn/keptn/issues/4061
> #4061 extended secretUtils

- pkg/api/models/uniform.go
- pkg/api/utils/uniformUtils.go
closes: https://github.com/keptn/keptn/issues/4273
> removed deploymentname and status from uniform integration model

- go.mod
- go.sum
- pkg/api/models/error.go
- pkg/api/models/log.go
- pkg/api/utils/logUtils.go
- pkg/api/utils/logUtils_test.go
- pkg/api/utils/secretUtils.go
- pkg/api/utils/uniformUtils.go
Needed for github.com/keptn/keptn/issues/4030
> Log API utils

- releasenotes/releasenotes_V0.8.5.md
> Prepare v0.8.5

- pkg/lib/v0_2_0/events.go
> Added convenience functions for determining event types

- pkg/api/models/uniform.go
Needed for https://github.com/keptn/keptn/issues/4615
> feat: Added LastSeen property to Uniform Integration (keptn/keptn#4615)

- pkg/api/models/keptn_context_extended_c_e.go
- pkg/api/models/keptn_context_extended_c_e_test.go
> feat: Added Validate() method for KeptnContextExtendedCE struct (keptn/keptn/#4652)

- pkg/api/utils/sequenceUtils.go
- pkg/api/utils/sequenceUtils_test.go
part of: https://github.com/keptn/keptn/issues/3785
> feat(go-utils): implemented sequence control client

- .github/workflows/auto-pr.yml
- updates the auto PR title to adhere to the semantic PR config
> ci: Update auto PR title to adhere to semantic PR config

- pkg/api/models/uniform.go
- pkg/api/models/uniform_response.go
- pkg/api/models/uniform_test.go
- pkg/api/utils/uniformUtils.go
part of https://github.com/keptn/keptn/issues/4437
> feat: Support for multiple uniform subscriptions

- pkg/common/mongoutils/mongo.go
- pkg/common/mongoutils/mongo_test.go
- pkg/common/strutils/strutils.go
- pkg/common/strutils/strutils_test.go
> feat: Added helper function to get mongodb connection string based on env vars (#5369)

- pkg/api/utils/healthCheck.go
- adds a function to return an health handler
keptn/keptn#5303
> feat: health handler (#5303 )

- pkg/lib/v0_2_0/events.go
fixes https://github.com/keptn/keptn/issues/5980
> fix(go-utils): set target also in `EventSender::Send`

- pkg/lib/keptn/keptn_base.go
- pkg/lib/keptn/keptn_base_test.go
Signed-off-by: Giovanni Liva <giovanni.liva@dynatrace.com>
Fixes https://github.com/keptn/keptn/issues/6061
> fix: Make SLI.indicators required

- pkg/lib/v0_2_0/status.go
part of https://github.com/keptn/keptn/issues/5604
> feat: added "aborted" as possible StatusType

- pkg/lib/v0_2_0/getaction.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
- this pr is used here keptn/keptn#6258
- adds a get-action data structure to change remediations events as in here:
keptn/keptn/#4206
> feat: Added get-action data with action index (keptn/keptn/#4206)

- pkg/lib/v0_2_0/evaluation.go
- adds ComparedValues
keptn/keptn#5496
> feat: added ComparedValues to SLIResult (keptn/#5496)

- pkg/api/utils/apiServiceUtils.go
- pkg/api/utils/projectUtils.go
- adds a error check in getProject() function causing segmentation fault in cli unit tests in keptn/keptn repository
Bind with #6288
> fix: Add error check when creating requests

- pkg/api/utils/apiUtils.go
- pkg/api/utils/authUtils.go
- pkg/api/utils/client.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/logUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/secretUtils.go
- pkg/api/utils/sequenceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
- pkg/api/utils/uniformUtils.go
This PR introduces interfaces for each and every API offered by `APISet` to make testability on the callee side smoother.
> feat: Introduced interfaces for different types of APIs

- pkg/common/oauth2/discovery.go
- pkg/common/oauth2/discovery_test.go
This PR adds common functionality of OAuth inside a `oauthutils` package.
For now, only oauth discovery is shared in this package.
More to follow.
> feat: added oauthutils package

- pkg/api/models/error.go
- pkg/api/utils/apiServiceUtils.go
- pkg/api/utils/apiUtils.go
- pkg/api/utils/errors.go
- pkg/api/utils/eventUtils.go
- pkg/api/utils/logUtils.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/secretUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
closes: https://github.com/keptn/keptn/issues/6912
> fix: Enhance error handling in api utils

- pkg/api/models/evaluation.go
- pkg/api/models/keptn_context_extended_c_e.go
- pkg/api/models/keptn_context_extended_c_e_test.go
- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/events_test.go
- adds --git-commit-id flag to CLI
relates https://github.com/keptn/keptn/issues/6673
> feat: Add --git-commit-id flag to CLI

- pkg/api/models/create_project.go
- pkg/api/models/project.go
- support authentication to git remote repository via proxy
Fixes [#6801](https://github.com/keptn/keptn/issues/6801)
> feat: Support authentication via proxy

- pkg/api/models/create_project.go
- pkg/api/models/project.go
> fix: Rename proxySecure to proxyInsecure

- pkg/api/models/create_project.go
- pkg/api/models/project.go
> feat: Support PEM Certificate

- pkg/api/models/evaluation.go
- pkg/lib/v0_2_0/action.go
- pkg/lib/v0_2_0/deployment.go
- pkg/lib/v0_2_0/evaluation.go
- pkg/lib/v0_2_0/events.go
- pkg/lib/v0_2_0/release.go
- pkg/lib/v0_2_0/test.go
Fixes keptn/keptn#6745
breaking change !!
> chore: Removed unneeded Git Commit from finished events

- pkg/api/models/metadata.go
- adds new parameters to metadata model
Fixes #1234523
> fix(go-utils): Add parameters to metadata model

- pkg/api/models/metadata.go
> fix(go-utils): Make AutomaticProvisioning parameter required in metadata model

- pkg/api/models/create_project.go
- pkg/api/models/expanded_project.go
- pkg/api/models/project.go
- make the parameter required, so when it is default set to false, it will be available in the resulting request
> fix(go-utils): Make GitProxyInsecure parameter required

- pkg/api/models/create_project.go
- pkg/api/models/expanded_project.go
- pkg/api/models/project.go
Related to https://github.com/keptn/keptn/issues/7363
Note: This is a breaking change regarding the project creation/update API
Parts of Keptn core will need to be updated before we can update to the resulting version of go-utils (will be done in the scope of https://github.com/keptn/keptn/issues/7363)
> feat: Rename GitProxyInsecure to InsecureSkipTLS since that property should not only be tied to the proxy feature

- pkg/lib/v0_2_0/keptn.go
- pkg/lib/v0_2_0/keptn_test.go
Closes https://github.com/keptn/keptn/issues/7409
> fix: Gracefully handle missing event labels

- pkg/api/models/create_project.go
- pkg/api/models/expanded_project.go
- pkg/api/models/git_credentials.go
- pkg/api/models/project.go
- refactors git remote repository credentials models to be mutable from only one place
> feat: Refactor git remote repository credentials models

- pkg/api/utils/internal.go
- pkg/api/utils/internal_test.go
- pkg/api/utils/projectUtils.go
- pkg/api/utils/resourceUtils.go
- pkg/api/utils/serviceUtils.go
- pkg/api/utils/shipyardControllerUtils.go
- pkg/api/utils/stageUtils.go
- pkg/api/utils/v2/internal.go
- pkg/api/utils/v2/internal_test.go
- pkg/api/utils/v2/projectUtils.go
- pkg/api/utils/v2/resourceUtils.go
- pkg/api/utils/v2/serviceUtils.go
- pkg/api/utils/v2/shipyardControllerUtils.go
- pkg/api/utils/v2/stageUtils.go
- pkg/lib/keptn/keptn_base.go
- pkg/lib/keptn/keptn_base_test.go
- pkg/sdk/internal/config/config.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
- substitute configuration service with resource service
BREAKING CHANGE
> chore: Changed configuration-service to resource-service

- pkg/sdk/connector/nats/nats.go
Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
- fixes keptn/keptn#8401 by adding a `sync.Mutex` to `(nc *NatsConnector) ensureConnection()` to prevent race conditions relating to the `connection` field of `nats.NatsConnector`
> fix: Add mutex to protect `connection` in `nats.NatsConnector`

- pkg/sdk/connector/controlplane/controlplane.go
- pkg/sdk/connector/controlplane/controlplane_test.go
- pkg/sdk/connector/eventsource/eventsource.go
- pkg/sdk/connector/eventsource/http/http.go
- pkg/sdk/connector/eventsource/nats/nats.go
- pkg/sdk/connector/eventsource/nats/nats_test.go
- pkg/sdk/connector/fake/eventsource.go
Closes [keptn/keptn#8446](https://github.com/keptn/keptn/issues/8446)
> fix: Shut down control plane components before calling wg.Wait()

- .github/workflows/tests.yml
- codecov.yml
- examples/go-sdk/go.mod
- examples/go-sdk/go.sum
- examples/go-sdk/main.go
- pkg/sdk/internal/api/initializer.go
- pkg/sdk/internal/api/initializer_test.go
- pkg/sdk/keptn.go
- pkg/sdk/keptn_test.go
closes https://github.com/keptn/keptn/issues/8453
> chore: increase test coverage of go-sdk

- pkg/api/models/expanded_project.go
> feat: Introduce IsUpstreamAutoProvisioned to ExpandedProject model
